import = ["/home/trimclain/.config/alacritty/themes/machiatto.toml", "/home/trimclain/.config/alacritty/themes/lighthouse.toml", "/home/trimclain/.config/alacritty/themes/dracula.toml", "/home/trimclain/.config/alacritty/themes/blood_moon.toml", "/home/trimclain/.config/alacritty/themes/doom_one.toml", "/home/trimclain/.config/alacritty/themes/palenight.toml", "/home/trimclain/.config/alacritty/themes/ubuntu.toml", "/home/trimclain/.config/alacritty/themes/campbell.toml", "/home/trimclain/.config/alacritty/themes/xterm.toml", "/home/trimclain/.config/alacritty/themes/hyper.toml"]

[colors.primary]
background = "#282c34"

[cursor.style]
blinking = "Never"
shape = "Beam"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.1"

[font]
size = 13.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiBold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiBold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 5000

[window]
dynamic_padding = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
