###############################################################################
#                                                                             #
#    ████████╗██████╗ ██╗███╗   ███╗ ██████╗██╗      █████╗ ██╗███╗   ██╗     #
#    ╚══██╔══╝██╔══██╗██║████╗ ████║██╔════╝██║     ██╔══██╗██║████╗  ██║     #
#       ██║   ██████╔╝██║██╔████╔██║██║     ██║     ███████║██║██╔██╗ ██║     #
#       ██║   ██╔══██╗██║██║╚██╔╝██║██║     ██║     ██╔══██║██║██║╚██╗██║     #
#       ██║   ██║  ██║██║██║ ╚═╝ ██║╚██████╗███████╗██║  ██║██║██║ ╚████║     #
#       ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝     #
#                                                                             #
#        Arthur McLain (trimclain)                                            #
#        mclain.it@gmail.com                                                  #
#        https://github.com/trimclain                                         #
#                                                                             #
###############################################################################

# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Docs: https://alacritty.org/config-alacritty.html

# More Colorschemes: https://github.com/alacritty/alacritty-theme
[general]
import = [
    "~/.config/alacritty/base.toml",

    # "~/.config/alacritty/themes/campbell.toml",
    # "~/.config/alacritty/themes/xterm.toml",
    "~/.config/alacritty/themes/hyper.toml",

    # Load local config file if it exists
    "~/.config/alacritty/local.toml",
]
