#!/usr/bin/env bash

# Sixel
image() {
    if [[ "$TERM" == "alacritty" ]]; then
        echo "Alacritty doesn't support images"
        return
    fi

    file=$1
    w=$2
    h=$3
    x=$4
    y=$5

    if [[ -n $TMUX ]]; then
        # The only way that works in tmux
        geometry="$(("$w"-2))x$h"
        chafa "$file" -s "$geometry"
    else
        # This doesn't work at all in lf
        # chafa "$file" -f sixel -s "$geometry"

        kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
        exit 1
    fi
}

# Ueberzugpp
# https://github.com/jstkdng/ueberzugpp/blob/master/scripts/lf/lfub
# image() {
#     FILE_PATH="$1"
#     X=$4
#     Y=$5
#     MW=$(($2-1))
#     MH=$3
#     ueberzugpp cmd -s $UB_SOCKET -a add -i PREVIEW -x $X -y $Y --max-width $MW --max-height $MH -f "$FILE_PATH"
#     exit 1
# }

# Kitty Preview (doesn't work in tmux; works in wezterm)
# image() {
#     file=$1
#     w=$2
#     h=$3
#     x=$4
#     y=$5
#     # if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
#     kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
#     exit 1
#     # fi
# }

batorcat() {
    file="$1"
    shift
    if command -v bat > /dev/null 2>&1; then
        bat --color=always --style=plain --pager=never "$file" "$@"
    elif command -v batcat > /dev/null 2>&1; then
        # thanks ubuntu
        batcat --color=always --style=plain --pager=never "$file" "$@"
    else
        cat "$file"
    fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
        # TODO:
        # *.tgz|*.tar.gz) tar tzf "$1" ;;
        # *.tar.bz2|*.tbz2) tar tjf "$1" ;;
        # *.tar.txz|*.txz) xz --list "$1" ;;
        # *.tar) tar tf "$1" ;;
        # *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
        # *.rar) unrar l "$1" ;;
        # *.7z) 7z l "$1" ;;
        # *.[1-8]) man "$1" | col -b ;;
        # *.o) nm "$1" ;;
        # *.torrent) transmission-show "$1" ;;
        # *.iso) iso-info --no-header -l "$1" ;;
        # *.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
        # *.doc) catdoc "$1" ;;
        # *.docx) docx2txt "$1" - ;;
        # *.xls|*.xlsx)
        #     ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batorcat --language=csv
        #     ;;
        # *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
        #     exiftool "$1"
        #     ;;

        # Works only with ueberzugpp
    *.pdf)
        ## PREVIEW IMAGE:
        # [ ! -f "${CACHE}.jpg" ] && \
            #     pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        # image "${CACHE}.jpg" "$2" "$3" "$4" "$5"

        ## PRINT METADATA:
        pdfinfo "$1"
        ;;

        # *.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
        #     [ ! -f "${CACHE}.jpg" ] && \
            #         ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
        #     image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
        #     ;;
    *.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.gif|*.jfif)
        ## PREVIEW IMAGE:
        # image "$1" "$2" "$3" "$4" "$5"

        ## PRINT METADATA: requires imagemagick
        identify -format "%f %m %G %[colorspace] %b\n" "$1"
        ;;
    *.svg)
        ## PREVIEW IMAGE: requires imagemagick
        # [ ! -f "${CACHE}.jpg" ] && \
            #     convert "$1" "${CACHE}.jpg"
        # image "${CACHE}.jpg" "$2" "$3" "$4" "$5"

        ## PRINT METADATA: requires imagemagick
        identify -format "%f %m %G %[colorspace] %b\n" "$1"
        ;;
    *.ttf)
        ## PREVIEW IMAGE: requires imagemagick
        # TODO: can this be opened in the terminal?
        #display "$1"
        ;;
    *)
        batorcat "$1"
        ;;
esac
exit 0
