# Docs: https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# A continuation prompt that displays two filled-in arrows
#continuation_prompt = '▶▶ ' # default: "[∙](bright-black) "

scan_timeout = 10 # default: 30

# Docs: https://starship.rs/config/#default-prompt-format
# Default: format = "$all"
format = """
$all\
$fill\
$time\
$line_break\
$character"""

# INFO: to use more nerd font icons: https://starship.rs/presets/nerd-font

[directory]
read_only = " 󰌾" # default: "🔒"

[python]
symbol = " " # default: "🐍 "
version_format = "v${major}.${minor}" # default: "v${raw}"

[cmd_duration]
min_time = 3000 # default: 2000
# SOMEDAY: $duration has no space, e.g. 16m40s. Create a PR to allow that.
format = "took [$duration]($style) "

[fill]
symbol = " " # default: "."

[time]
disabled = false
format = "[$time]($style) " # default: "at [$time]($style) "
time_format = "%T"
