[General]
contrastOpacity=188
disabledTrayIcon=false
drawColor=#008000
savePath=/home/trimclain
showDesktopNotification=false
showHelp=false
showStartupLaunchMessage=false
startupLaunch=false
; Wayland Fix: https://flameshot.org/docs/guide/wayland-help/
disabledGrimWarning=true
useGrimAdapter=true
