# Docs: https://github.com/aome510/spotify-player/blob/master/docs/config.md
client_id = "d420a117a32841c2b3474932e49fb54b"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album} • {genres}
{metadata}"""
playback_metadata_fields = [
    "repeat",
    "shuffle",
    "volume",
    "device",
]
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
explicit_icon = "(E)"
border_type = "Plain"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
genre_num = 2
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
enable_media_control = true
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "spotify-player"
seek_duration_secs = 5
sort_artist_albums_by_type = false

# FIX: this does nothing for some reason
theme = "tokyonight"

# {{{ Notifications
# default: true
enable_notify = false
notify_timeout_in_secs = 0
notify_transient = false
notify_streaming_only = false

[notify_format]
summary = "{track} • {artists}"
body = "{album}"
# }}}

[layout]
# default: "Top"
playback_window_position = "Bottom"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 90
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
# vim:foldmethod=marker
