# Docs:
# Default Keymaps: https://github.com/aome510/spotify-player/blob/master/README.md#commands
# All Actions: https://github.com/aome510/spotify-player/blob/master/README.md#actions

# Example:
# [[keymaps]]
# command = "NextTrack"
# key_sequence = "g n"
# [[keymaps]]
# command = "PreviousTrack"
# key_sequence = "g p"
# [[keymaps]]
# command = "Search"
# key_sequence = "C-c C-x /"
# [[keymaps]]
# command = "ResumePause"
# key_sequence = "M-enter"
# [[keymaps]]
# command = "None"
# key_sequence = "q"
# [[keymaps]]
# command = { VolumeChange = { offset = 1 } }
# key_sequence = "-"
# [[keymaps]]
# command = { SeekForward = { duration = 10 } }
# key_sequence = "E"
# [[keymaps]]
# command = { SeekBackward = { } }
# key_sequence = "Q"

# C-q -> q
[[keymaps]]
command = "PreviousPage"
key_sequence = "q"

# q -> Q
[[keymaps]]
command = "Quit"
key_sequence = "Q"

# Tab good but L more vim-like
[[keymaps]]
command = "FocusNextWindow"
key_sequence = "L"

# S-Tab good but H more vim-like
[[keymaps]]
command = "FocusPreviousWindow"
key_sequence = "H"
