# Docs at https://github.com/JohnnyMorganz/StyLua#options
syntax = "All" # All, Lua51, Lua52, Lua53, Lua54, LuaJIT, Luau
column_width = 120
line_endings = "Unix" # Unix, Windows
indent_type = "Spaces" # Spaces, Tabs
indent_width = 4
quote_style = "AutoPreferDouble" # AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle
call_parentheses = "Always" # Always, NoSingleString, NoSingleTable, None, Input
collapse_simple_statement = "Never" # Never, FunctionOnly, ConditionalOnly, Always
space_after_function_names = "Never" # Never, Definitions, Calls, Always

[sort_requires]
enabled = false
