[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#494D56", italic = true }

# Hovered
hovered         = { bg = "#26343F" }
preview_hovered = { bg = "#26343F" }

# Find
find_keyword  = { fg = "#1A1D23", bg = "#EB8332", bold = true }
find_position = { fg = "#50A4E9", bg = "#26343F", bold = true }

# Marker
marker_copied   = { fg = "#75AD47", bg = "#75AD47" }
marker_cut      = { fg = "#F8747E", bg = "#F8747E" }
marker_marked   = { fg = "#CC83E3", bg = "#CC83E3" }
marker_selected = { fg = "#50A4E9", bg = "#50A4E9" }

# Tab
tab_active   = { fg = "#ADB0BB", bg = "#1A1D23" }
tab_inactive = { fg = "#494D56", bg = "#111317" }
tab_width    = 1

# Count
count_copied   = { fg = "#9B9FA9", bg = "#75AD47" }
count_cut      = { fg = "#9B9FA9", bg = "#F8747E" }
count_selected = { fg = "#9B9FA9", bg = "#50A4E9" }
# Border
border_symbol = "│"
border_style  = { fg = "#3A3E47" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3A3E47", bg = "#3A3E47" }

# Mode
mode_normal = { fg = "#1A1D23", bg = "#50A4E9", bold = true }
mode_select = { fg = "#1A1D23", bg = "#CC83E3", bold = true }
mode_unset  = { fg = "#1A1D23", bg = "#F8747E", bold = true }

# Progress
progress_label  = { fg = "#494D56", bold = true }
progress_normal = { fg = "#1A1D23" }
progress_error  = { fg = "#F8747E" }

# Permissions
permissions_t = { fg = "#50A4E9" }
permissions_r = { fg = "#D09214" }
permissions_w = { fg = "#F8747E" }
permissions_x = { fg = "#75AD47" }
permissions_s = { fg = "#3A3E47" }

[select]
border   = { fg = "#3A3E47" }
active   = { fg = "#9B9FA9",  bg = "#26343F" }
inactive = { fg = "#9B9FA9" }

# Input
[input]
border   = { fg = "#50A4E9" }
title    = { fg = "#50A4E9" }
value    = { fg = "#CC83E3" }
selected = { bg = "#26343F" }

# Completion
[completion]
border   = { fg = "#50A4E9" }
active   = { fg = "#9B9FA9", bg = "#26343F" }
inactive = { fg = "#9B9FA9" }

# Tasks
[tasks]
border  = { fg = "#3A3E47" }
title   = { fg = "#50A4E9" }
hovered = { fg = "#9B9FA9", bg="#26343F" }

# Which
[which]
cols = 3
mask            = { bg = "#16181D" }
cand            = { fg = "#00B298" }
rest            = { fg = "#50A4E9" }
desc            = { fg = "#CC83E3" }
separator       = "  "
separator_style = { fg = "#3A3E47" }

# Notify
[notify]
title_info  = { fg = "#50A4E9" }
title_warn  = { fg = "#D09214" }
title_error = { fg = "#F8747E" }

# Help
[help]
on      = { fg = "#75AD47" }
run     = { fg = "#CC83E3" }
hovered = { bg = "#26343F" }
footer  = { fg = "#9B9FA9", bg = "#1A1D23" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#DFAB25" },

	# Media
	{ mime = "{audio,video}/*", fg = "#DD97F1" },

	# Archives
	{ mime = "application/*zip", fg = "#FF838B" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#FF838B" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#4AC2B8" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#FF838B" },

	# Special files
	{ name = "*", is = "orphan", bg = "#FF838B" },
	{ name = "*", is = "exec"  , fg = "#87C05F" },

	# Fallback
	{ name = "*/", fg = "#5EB7FF" }
]
