vim.g.sonokai_style = 'andromeda' -- options: 'default', 'atlantis', 'andromeda', 'shusia', 'maia', 'espresso'
-- vim.g.sonokai_disable_italic_comment = 0 -- options: 0, 1
-- vim.g.sonokai_enable_italic = 0 -- options: 0, 1
-- vim.g.sonokai_cursor = 'auto' -- options: 'auto', 'red', 'orange', 'yellow', 'green', 'blue', 'purple'
-- vim.g.sonokai_transparent_background = 0 -- options: 0, 1, 2
-- vim.g.sonokai_menu_selection_background = 'blue' -- options: 'blue', 'green', 'red'
-- vim.g.sonokai_spell_foreground = 'none' -- options: 'none', 'colored'
-- vim.g.sonokai_show_eob = 1 -- options: 1, 0
-- vim.g.sonokai_diagnostic_text_highlight = 0 -- options: 0, 1
-- vim.g.sonokai_diagnostic_line_highlight = 0 -- options: 0, 1
-- vim.g.sonokai_diagnostic_virtual_text = 'grey' -- options: 'grey', 'colored'
-- -- vim.g.sonokai_current_word = ? -- Available values:   'grey background', 'bold', 'underline', 'italic' Default value:      'grey background' when not in transparent mode, 'bold' when in transparent mode.
-- vim.g.sonokai_disable_terminal_colors = 0 -- options: 0, 1
-- vim.g.sonokai_lightline_disable_bold = 0 -- options: 0, 1
vim.g.sonokai_better_performance = 1 -- options: 0, 1
-- vim.g.sonokai_colors_override = {} -- Override color palette. The available keys can be found in /path/to/sonokai/autoload/sonokai.vim
